name: doxbox
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  provider: ^6.0.3
  path_provider: ^2.0.11
  path: ^1.8.1
  hive:
  hive_flutter:
  csv:
  file_picker:
  page_transition:
  fluttertoast: ^8.0.9
  another_flushbar:
  clipboard:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
